### ISSUE TITLE
Why app link for playstore is broken? Is the project dead?

### ISSUE THREAD

**Issue by rajan-31** [Maxr1998/MaxLock#161]
I was looking for open source app lock like this. But, unfortunately I don't see any way to install it. The google play-store link is broken and it is not available. If the project is not maintained anymore please mention it on README.

**Comment by Maxr1998** [comment]
I removed it from the Play Store to not risk any policy strikes. The last releases can be downloaded over at XDA and from the Xposed repo.
Currently, the project is in fact "hibernated"; and while I still plan to get back to it at some point, the chances are getting smaller and smaller every day. Since the codebase is quite old already with quite a few bugs and no (guaranteed) compatibility with new Android versions, I should probably add a note to the README and archive this repository for now.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/Maxr1998/MaxLock/issues/161#issuecomment-850006214

@Maxr1998, I've created https://github.com/Maxr1998/MaxLock/pull/166/commits/f2cd26af301d1862c6967de50ed583257811eab9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L9 consequently.
